import { GoogleGenAI } from "@google/genai";

const MODEL_NAME = "gemini-2.5-flash-image";

export interface ReferenceImage {
  data: string; // base64
  mimeType: string;
}

export async function generateThumbnail(title: string, references: ReferenceImage[], mode: 'thumbnail' | 'logo' = 'thumbnail') {
  const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || "" });

  const thumbnailInstruction = `You are a professional YouTube Thumbnail Designer. 
I have provided reference images that define my personal brand. 
1. **Visual Consistency:** Always use my face/image from the reference files. This is the only constant element.
2. **Creative Variety:** For every generation, create a **completely new and unique style**. Do not repeat the same background or layout. Experiment with different vibrant colors, lighting effects, 3D elements, and modern graphic design trends. Each thumbnail must look fresh and distinct.
3. **Contextual Elements:** Analyze the provided video title. If it mentions specific apps or AI (e.g., 'ChatGPT', 'Python'), include their official logos. If it mentions 'Mobile', show a high-quality mobile phone interface relevant to the topic.
4. **Layout:** Be creative with the text and image placement. Use bold, readable typography that changes style to match the new theme of each generation.
5. **Direct Execution:** Generate the final thumbnail image immediately. Do not include any text in your response other than the image itself.`;

  const logoInstruction = `You are a professional Logo and Brand Identity Designer.
Your task is to create a high-quality, professional logo based on the provided description.
1. **Design Principles:** Create clean, scalable, and memorable logos. Use modern design trends like minimalism, gradients, or 3D glassmorphism where appropriate.
2. **Style Consistency:** If reference images are provided, take inspiration from their color palette and overall aesthetic, but create a unique logo mark.
3. **Versatility:** Ensure the logo looks good on both light and dark backgrounds.
4. **Direct Execution:** Generate the final logo image immediately on a clean background. Do not include any text in your response other than the image itself.`;

  const systemInstruction = mode === 'thumbnail' ? thumbnailInstruction : logoInstruction;

  const referenceParts = references.map(ref => ({
    inlineData: {
      data: ref.data.split(',')[1], // remove data:image/png;base64,
      mimeType: ref.mimeType
    }
  }));

  const promptPart = {
    text: mode === 'thumbnail' 
      ? `Generate a UNIQUE and CREATIVE YouTube thumbnail for the title: "${title}". Use my face from the references, but create a COMPLETELY NEW background and style. Timestamp: ${Date.now()}`
      : `Generate a professional and modern LOGO for: "${title}". Make it unique, creative, and high-quality. Timestamp: ${Date.now()}`
  };

  try {
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: {
        parts: [...referenceParts, promptPart]
      },
      config: {
        systemInstruction: systemInstruction,
        imageConfig: {
          aspectRatio: mode === 'thumbnail' ? "16:9" : "1:1"
        }
      }
    });

    const imagePart = response.candidates?.[0]?.content?.parts.find(p => p.inlineData);
    if (imagePart?.inlineData) {
      return `data:${imagePart.inlineData.mimeType};base64,${imagePart.inlineData.data}`;
    }
    
    throw new Error("No image was generated by the model.");
  } catch (error: any) {
    console.error("Error generating thumbnail:", error);
    
    // Check for quota/rate limit errors
    if (error.message?.includes("429") || error.message?.includes("RESOURCE_EXHAUSTED")) {
      throw new Error("API Quota Exceeded: You've reached the limit for free image generation. Please wait a minute or connect a paid API key in settings.");
    }
    
    throw error;
  }
}
